pool: MyAgentPool
steps:
- bash: echo hello world

- main


  name: Default 

variables:
  buildConfiguration: 'Release'

pasos: 
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'